import { Router, type IRouter } from "express";
import { z } from "zod";
import { adminWorkerExists, createSession, deleteSession, deleteWorkerMedia, ensureBootstrapAdmin, getAdminByEmail, getContentBlock, getSetting, listAdminWorkers, createWorker, saveWorkerMedia, updateWorker, updateWorkerAvailability, updateWorkerStatus, listNationalities, listSkills, upsertContentBlock, upsertSetting, upsertTaxonomy, writeAudit } from "../lib/repository";
import { createSessionToken, hashPassword, hashSessionToken, verifyPassword } from "../lib/auth";
import { requireAdmin, requireRole } from "../middlewares/admin-auth";
import { createMediaUpload, mediaUploadPolicy, type AllowedMediaType } from "../lib/media-storage";

const router: IRouter = Router();
const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1).max(200) });
const workerSchema = z.object({
  publicCode: z.string().trim().regex(/^AHD-[0-9]{4,}$/i).optional(), displayName: z.string().trim().min(1).max(120), slug: z.string().optional(), nationalityId: z.string().min(1),
  age: z.number().int().min(18).max(100).nullable().optional(), currentCity: z.string().max(120).nullable().optional(), yearsExperience: z.number().int().min(0).max(80).nullable().optional(), saudiExperienceYears: z.number().int().min(0).max(80).nullable().optional(),
  publicSummaryEn: z.string().max(3000).nullable().optional(), publicSummaryAr: z.string().max(3000).nullable().optional(), languages: z.array(z.string().max(80)).max(10).optional(), internalNotes: z.string().max(5000).nullable().optional(),
  availabilityStatus: z.enum(["AVAILABLE", "ON_HOLD", "RESERVED", "TRANSFER_IN_PROGRESS", "TRANSFERRED", "UNAVAILABLE"]).optional(), publicationStatus: z.enum(["DRAFT", "PUBLISHED", "ARCHIVED"]).optional(), isFeatured: z.boolean().optional(), sortOrder: z.number().int().min(0).max(100000).optional(), skillIds: z.array(z.string()).max(50).optional(),
});
const taxonomySchema = z.object({ id: z.string().optional(), nameEn: z.string().trim().min(1).max(120), nameAr: z.string().trim().min(1).max(120), slug: z.string().optional(), isActive: z.boolean().optional(), sortOrder: z.number().int().min(0).max(100000).optional() });
const contentSchema = z.object({ contentEn: z.unknown().optional(), contentAr: z.unknown().optional(), isActive: z.boolean().optional() });
const mediaSchema = z.object({ url: z.string().url().max(2000).refine((value) => new URL(value).protocol === "https:", "Media URLs must use HTTPS"), altTextAr: z.string().trim().max(300).nullable().optional(), visibility: z.enum(["PUBLIC", "INTERNAL", "SENSITIVE"]).optional(), isPrimary: z.boolean().optional() });
const mediaUploadSchema = z.object({ contentType: z.enum(["image/jpeg", "image/png", "image/webp", "video/mp4"]), size: z.number().int().positive() });

router.post("/v1/admin/auth/login", async (req, res, next) => {
  try {
    const input = loginSchema.parse(req.body);
    if (process.env.AHD_ADMIN_EMAIL && process.env.AHD_ADMIN_PASSWORD) await ensureBootstrapAdmin(await hashPassword(process.env.AHD_ADMIN_PASSWORD));
    const admin = await getAdminByEmail(input.email);
    if (!admin || !admin.isActive || !(await verifyPassword(input.password, admin.passwordHash))) { res.status(401).json({ message: "Invalid email or password" }); return; }
    const token = createSessionToken();
    await createSession(admin.id, hashSessionToken(token), new Date(Date.now() + 8 * 60 * 60 * 1000));
    res.cookie("ahd_admin_session", token, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 8 * 60 * 60 * 1000, path: "/" });
    res.json({ data: { id: admin.id, email: admin.email, displayName: admin.displayName, role: admin.role } });
  } catch (error) { next(error); }
});

router.post("/v1/admin/auth/logout", async (req, res, next) => {
  try { const token = req.cookies?.ahd_admin_session; if (token) await deleteSession(hashSessionToken(token)); res.clearCookie("ahd_admin_session"); res.status(204).end(); } catch (error) { next(error); }
});

router.get("/v1/admin/auth/session", requireAdmin, (req, res) => { res.json({ data: req.admin }); });

router.use("/v1/admin", requireAdmin);
router.get("/v1/admin/workers", async (_req, res, next) => { try { res.json({ data: await listAdminWorkers() }); } catch (error) { next(error); } });
router.post("/v1/admin/workers", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const worker = await createWorker(workerSchema.parse(req.body)); await writeAudit({ actorAdminId: req.admin!.id, action: "worker.created", entityType: "Worker", entityId: String(worker.id), afterJson: worker }); res.status(201).json({ data: worker }); } catch (error) { next(error); } });
router.patch("/v1/admin/workers/:id", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const workerId = String(req.params.id); const worker = await updateWorker(workerId, workerSchema.partial().parse(req.body)); if (!worker) { res.status(404).json({ message: "Worker not found" }); return; } await writeAudit({ actorAdminId: req.admin!.id, action: "worker.updated", entityType: "Worker", entityId: workerId, afterJson: worker }); res.json({ data: worker }); } catch (error) { next(error); } });
router.post("/v1/admin/workers/:id/publish", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const workerId = String(req.params.id); const worker = await updateWorkerStatus(workerId, "PUBLISHED"); if (!worker) { res.status(404).json({ message: "Worker not found" }); return; } await writeAudit({ actorAdminId: req.admin!.id, action: "worker.published", entityType: "Worker", entityId: workerId, afterJson: worker }); res.json({ data: worker }); } catch (error) { next(error); } });
router.post("/v1/admin/workers/:id/unpublish", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const workerId = String(req.params.id); const worker = await updateWorkerStatus(workerId, "DRAFT"); if (!worker) { res.status(404).json({ message: "Worker not found" }); return; } await writeAudit({ actorAdminId: req.admin!.id, action: "worker.unpublished", entityType: "Worker", entityId: workerId, afterJson: worker }); res.json({ data: worker }); } catch (error) { next(error); } });
router.post("/v1/admin/workers/:id/archive", requireRole("SUPER_ADMIN", "ADMIN"), async (req, res, next) => { try { const workerId = String(req.params.id); const worker = await updateWorkerStatus(workerId, "ARCHIVED"); if (!worker) { res.status(404).json({ message: "Worker not found" }); return; } await writeAudit({ actorAdminId: req.admin!.id, action: "worker.archived", entityType: "Worker", entityId: workerId, afterJson: worker }); res.json({ data: worker }); } catch (error) { next(error); } });
router.patch("/v1/admin/workers/:id/availability", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const workerId = String(req.params.id); const status = z.object({ status: workerSchema.shape.availabilityStatus.unwrap() }).parse(req.body).status; const worker = await updateWorkerAvailability(workerId, status); if (!worker) { res.status(404).json({ message: "Worker not found" }); return; } await writeAudit({ actorAdminId: req.admin!.id, action: "worker.availability_changed", entityType: "Worker", entityId: workerId, afterJson: worker }); res.json({ data: worker }); } catch (error) { next(error); } });

router.get("/v1/admin/nationalities", async (_req, res, next) => { try { res.json({ data: await listNationalities(false) }); } catch (error) { next(error); } });
router.post("/v1/admin/nationalities", requireRole("SUPER_ADMIN", "ADMIN", "CONTENT_MANAGER"), async (req, res, next) => { try { const item = await upsertTaxonomy("nationalities", taxonomySchema.parse(req.body)); await writeAudit({ actorAdminId: req.admin!.id, action: "nationality.created", entityType: "Nationality", entityId: String(item.id), afterJson: item }); res.status(201).json({ data: item }); } catch (error) { next(error); } });
router.patch("/v1/admin/nationalities/:id", requireRole("SUPER_ADMIN", "ADMIN", "CONTENT_MANAGER"), async (req, res, next) => { try { const item = await upsertTaxonomy("nationalities", { ...taxonomySchema.parse(req.body), id: String(req.params.id) }); await writeAudit({ actorAdminId: req.admin!.id, action: "nationality.updated", entityType: "Nationality", entityId: String(item.id), afterJson: item }); res.json({ data: item }); } catch (error) { next(error); } });
router.get("/v1/admin/skills", async (_req, res, next) => { try { res.json({ data: await listSkills(false) }); } catch (error) { next(error); } });
router.post("/v1/admin/skills", requireRole("SUPER_ADMIN", "ADMIN", "CONTENT_MANAGER"), async (req, res, next) => { try { const item = await upsertTaxonomy("skills", taxonomySchema.parse(req.body)); await writeAudit({ actorAdminId: req.admin!.id, action: "skill.created", entityType: "Skill", entityId: String(item.id), afterJson: item }); res.status(201).json({ data: item }); } catch (error) { next(error); } });
router.patch("/v1/admin/skills/:id", requireRole("SUPER_ADMIN", "ADMIN", "CONTENT_MANAGER"), async (req, res, next) => { try { const item = await upsertTaxonomy("skills", { ...taxonomySchema.parse(req.body), id: String(req.params.id) }); await writeAudit({ actorAdminId: req.admin!.id, action: "skill.updated", entityType: "Skill", entityId: String(item.id), afterJson: item }); res.json({ data: item }); } catch (error) { next(error); } });
router.get("/v1/admin/content/:key", async (req, res, next) => { try { const block = await getContentBlock(String(req.params.key), false); if (!block) { res.status(404).json({ message: "Content not found" }); return; } res.json({ data: block }); } catch (error) { next(error); } });
router.patch("/v1/admin/content/:key", requireRole("SUPER_ADMIN", "ADMIN", "CONTENT_MANAGER"), async (req, res, next) => { try { const key = String(req.params.key); const block = await upsertContentBlock(key, contentSchema.parse(req.body)); await writeAudit({ actorAdminId: req.admin!.id, action: "content.updated", entityType: "ContentBlock", entityId: key, afterJson: block }); res.json({ data: block }); } catch (error) { next(error); } });
router.get("/v1/admin/settings/:key", async (req, res, next) => { try { const setting = await getSetting(String(req.params.key)); if (!setting) { res.status(404).json({ message: "Setting not found" }); return; } res.json({ data: setting }); } catch (error) { next(error); } });
router.patch("/v1/admin/settings/:key", requireRole("SUPER_ADMIN", "ADMIN", "CONTENT_MANAGER"), async (req, res, next) => { try { const key = String(req.params.key); const input = z.object({ value: z.string().trim().min(1).max(200) }).parse(req.body); const normalized = key === "whatsappNumber" ? input.value.replace(/[^0-9]/g, "") : input.value; if (key === "whatsappNumber" && !/^\d{8,15}$/.test(normalized)) throw new z.ZodError([{ code: "custom", path: ["value"], message: "Invalid WhatsApp number" }]); const setting = await upsertSetting(key, normalized); await writeAudit({ actorAdminId: req.admin!.id, action: "setting.updated", entityType: "SystemSetting", entityId: key, afterJson: { key } }); res.json({ data: setting }); } catch (error) { next(error); } });
router.post("/v1/admin/workers/:id/media/upload", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const workerId = z.string().uuid().parse(String(req.params.id)); if (!(await adminWorkerExists(workerId))) { res.status(404).json({ message: "Worker not found" }); return; } const input = mediaUploadSchema.parse(req.body); const policy = mediaUploadPolicy(input.contentType as AllowedMediaType); if (input.size > policy.maxBytes) { res.status(413).json({ message: "Media file is too large" }); return; } res.json({ data: await createMediaUpload(workerId, input.contentType as AllowedMediaType) }); } catch (error) { next(error); } });
router.post("/v1/admin/workers/:id/media", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const workerId = String(req.params.id); const media = await saveWorkerMedia({ ...mediaSchema.parse(req.body), workerId }); if (!media) { res.status(404).json({ message: "Worker not found" }); return; } await writeAudit({ actorAdminId: req.admin!.id, action: "worker.media_saved", entityType: "WorkerMedia", entityId: String(media.id), afterJson: media }); res.status(201).json({ data: media }); } catch (error) { next(error); } });
router.patch("/v1/admin/workers/:id/media/:mediaId", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const workerId = String(req.params.id); const media = await saveWorkerMedia({ ...mediaSchema.parse(req.body), id: String(req.params.mediaId), workerId }); if (!media) { res.status(404).json({ message: "Media not found" }); return; } await writeAudit({ actorAdminId: req.admin!.id, action: "worker.media_saved", entityType: "WorkerMedia", entityId: String(media.id), afterJson: media }); res.json({ data: media }); } catch (error) { next(error); } });
router.delete("/v1/admin/workers/:id/media/:mediaId", requireRole("SUPER_ADMIN", "ADMIN", "OPERATIONS"), async (req, res, next) => { try { const deleted = await deleteWorkerMedia(String(req.params.id), String(req.params.mediaId)); if (!deleted) { res.status(404).json({ message: "Media not found" }); return; } await writeAudit({ actorAdminId: req.admin!.id, action: "worker.media_deleted", entityType: "WorkerMedia", entityId: String(req.params.mediaId) }); res.status(204).end(); } catch (error) { next(error); } });

export default router;
